---@diagnostic disable: duplicate-set-field, undefined-global, lowercase-global
Ark_mod = RegisterMod("Ar", 1)
New_Lance = Isaac.GetItemIdByName("King's New Lance")
Legacy = Isaac.GetItemIdByName("King's Legacy")
Armor = Isaac.GetItemIdByName("King's Armor")
Crown = Isaac.GetItemIdByName("King's Crown")
Beauty = Isaac.GetItemIdByName("Nostalgia of Beauty")
Hatred = Isaac.GetItemIdByName("Talons of Hatred")
Golden_Chalice = Isaac.GetItemIdByName("Golden Chalice")
Coin_Operated = Isaac.GetItemIdByName("Coin-Operated Toy")
Chivalric_Commandments = Isaac.GetItemIdByName("Chivalric Commandments - New Edition")
Seaweed_Salad = Isaac.GetItemIdByName("Seaweed Salad")
Orange_Storm = Isaac.GetItemIdByName("Orange Storm")
Coffee_Candy = Isaac.GetItemIdByName("Coffee Plains Coffee Candy")
Screaming_Cherry = Isaac.GetItemIdByName("Screaming Cherry")
Antique_Coins = Isaac.GetItemIdByName("Antique Coins")
Flawless_Jadestone = Isaac.GetItemIdByName("Flawless Jadestone")
Admin_Access_Card = Isaac.GetItemIdByName("Game Room Admin Access Card")
Petting_Ticket = Isaac.GetItemIdByName("Ms. Christine Petting Ticket")
Shadow_Revenant = Isaac.GetItemIdByName("Shadow of Revenant")

require("scripts.EID")
include("scripts.functions")
include("scripts.characters")
include("scripts.curses")
include("scripts.enemies")
include("scripts.pockets")